services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: packages/backend
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://user1:password1@db:5432/db
    volumes:
      - ./packages/backend:/usr/src/app
    command: ["sh", "-c", "yarn migrate-prod && node dist/index.js"]

volumes:
  postgres_data:
